### ISSUE TITLE
Run time dependency resolve

### ISSUE THREAD

**Issue by sreeram180** [young-steveo/bottlejs#123]
how to do run time dependency resolve for provider/service, where function arguments can be assign before creating the instance of a service

```
var bottle = new Bottle();

function modalcomponent($modalinstace,$modaldata,someservice){
 //code
}
bottle.service("modalcomponent",modalcomponent,"modalinstace","$modaldata","someservice");

```
$modalinstace, $modadata will be change based component/controller. 

For example AngualrJs UI $uimodal controller function, where you can resolve controller argument during the run time.

**Comment by young-steveo** [comment]
Hi, @sreeram180, sorry for taking so long to get back to you; this issue flew under my radar for some reason.

I'm not sure I understand the scope of the question.  Are you asking how to inject something from angular into your service?

**Comment by young-steveo** [comment]
Closing for now; mention me in a comment if you're still having trouble.
