### ISSUE TITLE
Async factory method

### ISSUE THREAD

**Issue by matthew798** [young-steveo/bottlejs#140]
Sorry for not asking this on SO, but there is no bottlejs tag so I fear my question would never be answered...

I have an async method that resolves to an object that I'd like to register as a service.

`await Theme.getTheme(this.config.theme)`

I'm wondering if it's possible to register this as a factory and preserve it's asynchronicity.

**Comment by young-steveo** [comment]
Sorry, I was out of town for most of last week.

What you can do is return the promise from your factory and await the container property lookup, like so (assuming you are using bottle for all of your dependencies):

```js
bottle.factory('asyncTheme', container => {
    const Theme = container.Theme;
    const config = container.config;
    return Theme.getTheme(config.theme);
});

// then when you need it:
result = await bottle.container.asyncTheme;
```

Let me know if that makes sense!
