### ISSUE TITLE
Factories and Providers do not work if the `container` argument is defined

### ISSUE THREAD

**Issue by travislaynewilson** [young-steveo/bottlejs#187]
I tried following this sample script for the latest version `2.0.1`, and I get an error when trying to resolve it.

```
class Test() {}

const bottle = new Bottle();
bottle.factory('Test', function(container) {
  return new Test()
});

const svc = bottle.container.Test
```

Error: 
`TypeError: provider.$get is not a function`

Note that this error does not occur if the `container` argument is not defined in the factory function.

**Comment by young-steveo** [comment]
Hi, @travislaynewilson !

You have a syntax error in your example (should be `class Test {}` not `class Test() {}`)

Running your script gives the error: 

```bash
❯ node test.js
./test.js:3
class Test() {}
          ^

SyntaxError: Unexpected token '('
```

I ran the following updated version of your code using Bottlw 2.0.1 and did not get an error:

```js
const Bottle = require("./dist/bottle");

class Test {}
const bottle = new Bottle();
bottle.factory('Test', function(container) {
  return new Test()
});
const svc = bottle.container.Test
console.log(svc);
```

My output:

```bash
❯ node test.js
Test {}
```

**Comment by young-steveo** [comment]
Let me know if you can reproduce the error with an isolated test, and I'll re-open the issue.  Thanks!
