### ISSUE TITLE
Non singleton service

### ISSUE THREAD

**Issue by kenvunz** [young-steveo/bottlejs#19]
> A lot happened behind the scenes:

> 1. Bottle created a provider containing a factory function when you registered the Beer service.
> 2. When the bottle.container.Beer property was accessed, Bottle looked up the provider and executed the factory to build and return the Beer service.
> 3. The provider and factory were deleted, and the bottle.container.Beer property was set to be the Beer service instance. Accessing bottle.container.Beer in the future becomes a simple property lookup.

Does it mean that all services are considered as `singleton`? Is there anyway to instantiate a new `Beer` service every time `Bottle.container.Beer` is accessed?

**Comment by young-steveo** [comment]
Hi @kenvunz, sorry for the late reply but I was on holiday for a couple of weeks.

You are correct: services are singletons.

The functionality you are requesting has been suggested before; [here was my response](https://github.com/young-steveo/bottlejs/issues/15#issuecomment-61328109).  Essentially, I think it is counterintuitive to get a new instance every time you access an object property.

As a fallback, you can register a "factory" service, like so:

```js
var Beer = function() {};
bottle.value('Beer', Beer);
bottle.factory('Keg', function (c) {
    var Beer = c.Beer;
    return {
        getBeer : function() { return new Beer(); }
    };
});

var newBeer = bottle.container.Keg.getBeer();
```

**Comment by kenvunz** [comment]
@young-steveo 
yeah that's what I've ended up doing. It's less convenient, but does bring clarity to what the container do, so i reckon it's a good trade :+1:

**Comment by young-steveo** [comment]
@kenvunz If you're interested, [Version 1.4.0](https://github.com/young-steveo/bottlejs/releases/tag/v1.4.0) now supports a new method `instanceProvider` that pretty much implements my example above for you.

**Comment by kenvunz** [comment]
👍  nice!! will check it out, thanks for letting me know
