### ISSUE TITLE
Support a way of $registering a value without changing that value

### ISSUE THREAD

**Issue by robations** [young-steveo/bottlejs#24]
Hi, as far as I can tell there's no way to use `.register()` or `$register()` to set a value without adding the `$name` and `$type` properties on that value. There are some circumstances where it’s undesirable to change values ad hoc, for example where you have immutable objects (think `Object.freeze()`) or you have code that makes assumptions about the properties on the value.

Perhaps it would be possible to add another key, say `$value` that the register method could use?

```javascript
var myVal = {things: "here"};
var container = BottleJS.pop().container;

// instead of
myVal.$name = "example";
myVal.$type = "value";
container.$register(myVal);

// suggested
container.$register({$name: "example", $type: "value", $value: myVal});
```

**Comment by young-steveo** [comment]
I like the idea.

**Comment by robations** [comment]
I could probably send a PR at some point if that would help. The only disadvantage would be a bit of extra complexity in the register function, but probably this would only add a couple of lines.

**Comment by young-steveo** [comment]
@robations Currently `register` is just a [one-liner](https://github.com/young-steveo/bottlejs/blob/master/src/Bottle/register.js#L13) (albeit a lot is going on in that one line)

To support this functionality would be as simple as adding `$value`:

```js
return this[Obj.$type || 'service'].apply(this, [Obj.$name, Obj.$value || Obj].concat(Obj.$inject || []));
```

**Comment by robations** [comment]
It might be a good idea to allow falsey values:

```javascript
return this[Obj.$type || 'service'].apply(this, [Obj.$name, typeof Obj.$value === "undefined" || Obj].concat(Obj.$inject || []));
```

**Comment by robations** [comment]
Cool. I briefly started working on this too but was away/busy etc...

**Comment by young-steveo** [comment]
@robations I was going to bump the version to 1.1 for a different reason, and decided I might as well add this feature too.  Thanks for the suggestion!
