### ISSUE TITLE
Null dependency becomes undefined after first use.

### ISSUE THREAD

**Issue by nguyenl** [young-steveo/bottlejs#25]
When a dependency that is of null value is used a second time, it becomes undefined instead of null.  This only occurs when using the `factory()` method of defining a dependency. Using `value()` works fine.

For example: 

``` javascript

    var b = Bottle.pop('test');
    b.factory('foo', function(container) {
      return null;
    });
    console.log(b.container.foo);  // Prints out null, as it should
    console.log(b.container.foo); // Prints out undefined. The dependencies "foo" has been changed.

```

**Comment by young-steveo** [comment]
@nguyenl Interesting.  I'll look into it and release a patch version if needed.

**Comment by young-steveo** [comment]
Fixed in version 1.0.1

Thanks for the bug report!

**Comment by nguyenl** [comment]
No problem. 

I love BottleJS btw. Great work!

**Comment by young-steveo** [comment]
Thanks
