### ISSUE TITLE
Bottle#value behaviour

### ISSUE THREAD

**Issue by Lukinos** [young-steveo/bottlejs#32]
Hi, I wanted to use Bottle#value to store nested values, but I ran into troubles. I cannot set two values in the same nested container, because the nested container is overwritten each time I set a new value.

For instance:
```javascript
var b = new Bottle();
b.value('nested.thingone', '123');
b.value('nested.thingtwo', '321');
console.log(b.container.nested.thingone) // undefined
console.log(b.container.nested.thingtwo) // 321
```
Is it a bug ? Because in the test suite, this case is not tested.

Edit: Same happend with constant.

**Comment by young-steveo** [comment]
@Lukinos Interesting... thanks for the report.  I'll look into it and get back to you.

**Comment by young-steveo** [comment]
@Lukinos I can confirm this is a valid bug.  I'll fix it and issue a patch version.  Thanks!
