### ISSUE TITLE
Inspecting resolved/provided dependencies

### ISSUE THREAD

**Issue by dominics** [young-steveo/bottlejs#35]
I have several clients in my container that require shutting down. Trouble being that if I access them on the container instance to call `unref()` or `close()` or whathaveyou, they'll be instantiated, even if they weren't a dependency yet.

Would you consider adding something to the public API that would allow me to determine if a dependency has been resolved/provided yet? That way I can check if a dependency has been accessed before lazily disposing of it.

**Comment by cjsaylor** [comment]
@dominics As an alternative in the meantime, you could setup a middleware that would keep track of it:

```js
var shutdownClients = {};
bottle.middleware(function(service, next) {
    // this middleware will be executed for all services
    shutdownClients[service] = 1;
    next();
});
```

If you don't define what service the middleware is active for, it becomes active for all. Then, you could check the `shutdownClients` variable to see if it was set by the middleware to determine if you need to shut them down in your usecase.

**Comment by young-steveo** [comment]
@dominics I think @cjsaylor's suggestion will do for now. However, I'm putting together a collection of "useful extensions" for bottle.  I'll include something like this in the separate collection.

**Comment by dominics** [comment]
@cjsaylor Thanks, great suggestion. ("Why didn't I think of that?!")

**Comment by dominics** [comment]
@cjsaylor I'm actually having trouble applying that pattern. 

Is `service.$name` expected to be defined? The only use I can find in the documentation is for the low level `$register` function (https://github.com/young-steveo/bottlejs#containerregisterobj), but by the time the service is passed to middleware, it's resolved and doesn't have that property AFAICT.

`name` is in scope at https://github.com/young-steveo/bottlejs/blob/master/src/Bottle/middleware.js#L31, but doesn't seem accessible from the middleware itself.

Am I missing something?

**Comment by cjsaylor** [comment]
@dominics I guess the `$name` property only available if it is set when you define the service or when using the `$register` method.
