### ISSUE TITLE
Consider an async provider

### ISSUE THREAD

**Issue by young-steveo** [young-steveo/bottlejs#40]
https://github.com/young-steveo/bottlejs/pull/39 mentions a case where the user is attempting to resolve a service asynchronously by throwing an error in the provider factory until the service is resolvable.

This has me thinking that it would be nice if bottle offered an async provider api of some sorts.  I can think of two challenges for this:

* Keeping bottle < 5kb when minified and gzipped.  In other words, a full blown promise solution wouldn't be viable.
* Services are resolved via getters and property lookups: `bottle.container.SomeService`.  This doesn't easily translate to an asynchronous solution without some kind of promise-like object being returned.

**Comment by young-steveo** [comment]
An example of a possible definition api:

```js
bottle.asyncProvider('Thing', function(resolve, reject) {
    setTimeout(function() { // get something via AJAX, then
        resolve(function(container) {
            // this is the factory function that is normally
            // assigned to the $get property of the provider.
            return new Thing();
        });
    }, 1000);
});
```

I suppose there would have to be some kind of promise object returned when accessing `bottle.container.Thing`:

```js
bottle.container.Thing.then(function(Thing) {

});
```

The only thing I don't like about it as that there's nothing to inform the user that `Thing` is not the actual service.  I suppose `container.Thing` could maybe always resolve to `undefined` if it is async, and I could introduce a new method to get async services (or maybe all services, inclusive of async services):

```js
bottle.container.$get('Thing', function(Thing) {

});
```

**Comment by cjsaylor** [comment]
I think this sort of thing should remain in userland. For example, to accomplish what this API would be doing with current API functionality (using the example from #39):

```js
bottle.factory('asyncService', function(container) {
	return {
		getService: function(callback) {
			if (!window.asyncService) {
				Object.defineProperty(window, 'asyncService', {
					configurable: true,
					enumerable: true,
					set: function(value) {
						delete window.asyncService;
						window.asyncService = value;
						callback(value);
					}
				});
			} else {
				callback(window.asyncService);
			}
		}
	};
});

bottle.container.asyncService.getService(function(service) {
	// do stuff
});
```

This keeps the provider synchronous in definition that exposes an asynchronous API to be used. Since, I think this is an edge-case scenario, it should remain userland.

**Comment by young-steveo** [comment]
@cjsaylor I think I agree that bottle should always return a service, and the service should be responsible for async actions.

**Comment by esroyo** [comment]
> An example of a possible definition api:
> 
> ```js
> bottle.asyncProvider('Thing', function(resolve, reject) {
>     setTimeout(function() { // get something via AJAX, then
>         resolve(function(container) {
>             // this is the factory function that is normally
>             // assigned to the $get property of the provider.
>             return new Thing();
>         });
>     }, 1000);
> });
> ```
> 
> I suppose there would have to be some kind of promise object returned when accessing `bottle.container.Thing`:
> 
> ```js
> bottle.container.Thing.then(function(Thing) {
> 
> });
> ```

Indeed. By adopting the convention of preceding the service name with the  `async` keyword, the current API gets pretty usable:
```
  const bottle = new Bottle();
  bottle.factory('asyncInfo', function (container) {
    return fetch('https://raw.githubusercontent.com/young-steveo/bottlejs/master/README.md')
      .then(function (res) {
        return res.text();
      }).then(function (txt) {
        return {
          readme: txt
        };
      });
  });
  bottle.container.asyncInfo.then(function (info) { console.log(info.readme); });
```
I'm going with that.

Not having async resolution in the web environment feels strange. The discussion remembers me of how useless a sync `require()` would be in the browsers: https://requirejs.org/docs/why.html#4

**Comment by young-steveo** [comment]
@esroyo  I think your solution is quite good.  simply:

```js
bottle.factory("Readme", container => fetch("/README.md").then(res => res.text()));
bottle.container.Readme.then(text => console.log(text));
```
Prefixing with `async` is also a decent convention for a project to adopt.

Returning a Promise from `fetch` as your "service" is the best case scenario, since otherwise I would likely need to include promise plumbing in the core of bottle, and this would increase it's size (one of the design goals of bottle is to be useful while staying tiny).

**Comment by esroyo** [comment]
@young-steveo I totally support the tiny/simplicity point because it is paired here with flexibility, and that delivers power. I'm still amazed that I can do stuff like this: https://jsfiddle.net/e7dxsw9z/ :grin: 

Thanks for your work, kind regards :)
