### ISSUE TITLE
.get() method for container access

### ISSUE THREAD

**Issue by StyleT** [young-steveo/bottlejs#42]
Currently I can access containers inside Bottle via `bottle.container.container_name` property. It's not a very elegant way. I proposed this scheme:
```js
var Beer = function() { /* A beer service, :yum: */ };

var b = new Bottle();
b.service('Beer', Beer);

var beerInstance = b.get('Beer'); 
//instead of 
var beerInstance = b.container.Beer;
```

**Comment by young-steveo** [comment]
I'll consider it; though it's only really saving you three keystrokes.  In the meantime, you should be able to add this to your application:

```js
Bottle.prototype.get = function(service) {
    return this.container[service];
};
```

It won't handle dot notation, but it should cover most of your needs.

**Comment by StyleT** [comment]
I can do PR for this (with dot notation support) if you don't mind...

**Comment by young-steveo** [comment]
I don't mind, as long as the implementation is small-ish.  :+1:

**Comment by young-steveo** [comment]
I think I've changed my mind on this issue; adding a `.get` method to the bottle instance encourages the Service Locator pattern of which I'm not a fan.

In most cases, you won't want to be accessing services directly from the container in user-land code.  Instead, inject those services into the parent, or use a factory to encapsulate the service location.

**Comment by StyleT** [comment]
Ok :) Bad that we're using this pattern.

**Comment by young-steveo** [comment]
@StyleT I think the Service Locator works fine in two places: inside a factory, and getting the main app to init the project.

```js

// inside a factory
bottle.factory('Thing', function(container) {
    // use container to look up services.  Container is a Service Locator.
    let depend = container.Depend;

    // inject it in the Thing
    return new Thing(depend);
});
```

```js

// here is an example of using bottle as a service locator in a bad way:
let bottle = Bottle.pop('myApp');
let App = function() {
    this.stuff = bottle.container.Thing; // service locator outside of a factory
};
App.prototype.start = function() {};
let app = new App();
app.start();
```

Now you're using bottle as a Service Locator inside a constructor.  That's where it starts avoiding the benefits of DI.  Instead the above code should be written as:

```js
let bottle = Bottle.pop('myApp');
let App = function(Thing) {
    this.stuff = Thing;
};
App.prototype.start = function() {};
bottle.service('App', App, 'Thing');
let app = bottle.container.App;
app.start();
```
