### ISSUE TITLE
Browser safeness

### ISSUE THREAD

**Issue by bingomanatee** [young-steveo/bottlejs#58]
Have you determined how browser safe this is, and is there code which may not work on any particular browser version?

**Comment by young-steveo** [comment]
Bottle works in ES5 compliant environments (so basically ie9+).  As far as safety is concerned, snyc.io shows [no known vulnerabilities](https://snyk.io/test/github/young-steveo/bottlejs) (primarily because bottle has no dependencies).

**Comment by bingomanatee** [comment]
ok; so when babelized, its ok within the Babel profile window? thanks.
