### ISSUE TITLE
Unlimited nested containers & decorators & middlewars

### ISSUE THREAD

**Issue by pun-ky** [young-steveo/bottlejs#61]
Try to test in browser console:

`var b = new Bottle()`
undefined
`b.service('A.B.C', function () {});`
Bottle {id: 1, container: Object}
`b.decorator('A.B.C', function (service) { console.log('Decorator should be called for nested container services!'); });`
Bottle {id: 1, container: Object}
`b.container.A.B.C`
Object {}

As you can see, decorator is not called. I checked with registering service for 'A.B' but it works properly. I think that container should cover unlimited levels count.

I have a module system with packages aka Java's ;) c.g core.some.subpage.MyModule .
For each module I want to setup its own logger via decorator but I couldn't because of snippet above.

Please fix it somehow. Btw thanks for Bottle, almost matches my needs perfectly :) As a workaround I am just replacing '.' to '-' in my service name while registering but I am loosing that nice nested structured while accessing container.

**Comment by pun-ky** [comment]
what is more I noticed that if some service is referencing unregistered service with name with dot ... call on undefined object is occurring and error in console is shown regardless strict mode.

**Comment by young-steveo** [comment]
I'll have a look at it tonight.  Thanks for the bug report!

**Comment by young-steveo** [comment]
I have a pending fix.  Just need to test it.

**Comment by young-steveo** [comment]
@pun-ky Sorry for the delay (I've been preparing for a hurricane down here in Florida).  I'll post back here once the fix is functional.

**Comment by young-steveo** [comment]
@pun-ky I have created and pushed a fix [here](https://github.com/young-steveo/bottlejs/issues/64) that will go out with the next bottle release soon, but please be aware of #63.  Now that your decorators will work for nested containers, you may find that the isolation causes further issues (depending on the namespace you've chosen).
