### ISSUE TITLE
Way to clear nestedBottles/named bottles?

### ISSUE THREAD

**Issue by emilong** [young-steveo/bottlejs#62]
In our test suite, we create a new bottle for each instance and load all our factories. I did a bit of profiling and noticed that `nestedBottles` grows with each iteration.

What do the maintainers think of a way to clear `nestedBottles` and/or the named bottle store manually for situations like these? Given the existing behavior, I'd think it's too dangerous to try to guess when to clear these, but our suite does know the right time. 😄

If this sounds ok, I'm happy to open a PR.

Thanks!

**Comment by young-steveo** [comment]
I think this is a fine idea, however I'm working on a fix to #61 that changes some of the internals surrounding `nestedBottles`.  This won't resolve your issue, but it might change how the implementation would work.  I'll post back here when it's done.

**Comment by young-steveo** [comment]
@emilong The changes have been merged into master.  I think a flush of `nestedBottles` and/or `bottles` for named instances would be a welcome change.  `nestedBottles` is a list of bottles associated to the dot notation containers, and `bottles` is a hash of named bottle instances.

I wonder if the two could be merged, further reducing the code...

**Comment by emilong** [comment]
Cool, I'll take a look at it today and see if I can make any headway.
