### ISSUE TITLE
Reference variables

### ISSUE THREAD

**Issue by tagyoureit** [young-steveo/bottlejs#70]
Thanks for the previous question/answer.  But first, awesome job.  I really appreciate the flexibility of the module you wrote.  I have a pretty interdependent app and am grateful that I can easily modularize my code.  But, I'm not sure I'm doing a couple of things correctly, so another couple questions if I may.

Is there a way to have the container object and the local object be a reference to each other?  

a)  What I would like to accomplish is to have the var and the bottle.container.containername.var to be the same.    I think I understand they are separate objects once returned to the bottle, but maybe there is a better way?  Am I doing this correctly?  Should I just be using GLOBAL object instead of using bottlejs, or something else?   I end up referencing simple variables throughout the various places in my code and need to use the fully qualified bottle name because I want to make sure I'm setting the globally available variable.

```
var testvar = 'testing the var';
bottle.service('testvar', function() {
    return {
        testvar
    }
})

console.log('testvar: %s', testvar)  //testing the var
console.log('bottle.container.testvar.testvar: %s', bottle.container.testvar.testvar)  //testing the var
testvar = 'new val' 
console.log('testvar: %s', testvar)  //new val
console.log('bottle.container.testvar.testvar: %s', bottle.container.testvar.testvar)  //testing the var
bottle.container.testvar.testvar = 'container assign'
console.log('testvar: %s', testvar)  //new val
console.log('bottle.container.testvar.testvar: %s', bottle.container.testvar.testvar)  //container assign
```

This is a pretty simplified example of a more complex problem, but hope it illustrates my question.  

b) b) Are there any best practices/shortcuts to access the container vars/functions by name?  Mostly for readability, my code had some long lines in it already, but now it is very difficult to read.  

As an example...
Before:
logger.warn('Error writing pump packet \'%s\' to serial bus.  Tried %s times to write %s', strPumpActions[queuePacketsArr[0][packetFields.ACTION + 3]], msgWriteCounter.counter, msgWriteCounter.msgWrote)

After:
logger.warn('Error writing pump packet \'%s\' to serial bus.  Tried %s times to write %s', container.constants.strPumpActions[container.writePacket.queuePacketsArr[0][container.constants.packetFields.ACTION + 3]], container.writePacket.msgWriteCounter.counter, container.writePacket.msgWriteCounter.msgWrote)

Thanks!

**Comment by young-steveo** [comment]
Hi @tagyoureit, I'm glad you like the library.

a) the first problem you're having is not really a bottlejs issue; this is just how javascript works.  I'll give you an example that doesn't use bottle:

```js
var test = 'a';
var giveMeTest = function() {
    // This assigns the "current value" of the global `test` variable to
    // the property `test` of a new object and returns the object.
    // The value is copied; it's not a reference.
    return {
        test : test 
    };
};

var obj = giveMeTest();

test = 'b';

console.log(test); // This is 'b' because we just changed `test`
console.log(obj.test); // This is 'a' because that's what `test` was when we called the function
```

In javascript, objects are passed by value as a reference, but primitives are just passed by value; so changing a variable assignment is not by reference.

You could achieve what you're looking for if you used an object.  Something like this:

```js
var globalTest = { test : 'a' };
bottle.factory('test', function() {
    return globalTest;
});

var bottleTest = bottle.container.test;
console.log(globalTest === bottleTest); // true

globalTest.test = 'b';
console.log(bottleTest.test); // 'b'
```


b) for your second problem, it's hard to give specific advice; except to say that it looks like you're using bottle as a "Service Locator" instead of relying on Dependency Injection.  There are a lot of implied globals in your example, so you may not be able to change that now.

Without knowing much about the code itself, some advice would be to start using more variables.  something like:
```js
bottle.factory('PumpPacketWarningLogger', function(container) {
    var strPumpActions = container.strPumpActions;
    var msgWriteCounter = container.msgWriteCounter;
    var logger = container.logger;

    //  ... etc
});
```
