### ISSUE TITLE
Jasmine test setup doesn't work with newer versions of NPM

### ISSUE THREAD

**Issue by cjsaylor** [young-steveo/bottlejs#74]
NPM changed the file structure when they do installs and now they try to stick dependencies as high up as they can. The grunt-jasmine dependency is expecting `es5-shim` under the grunt-jasmine node-modules directory which is now in the root.

Tested with node `6.9.1` (npm `v3.10.8`).

Probably just needs an update to the grunt-contrib-jasmine dev dependency.

**Comment by young-steveo** [comment]
Hopefully it's resolved in a grunt-contrib-jasmine future version.
