### ISSUE TITLE
ES6 arrow functions support

### ISSUE THREAD

**Issue by oleksiipysanko** [young-steveo/bottlejs#77]
Hi, thanks for an awesome library!

I'm using ES6 arrow functions in modules where dependencies should be injected like:

```
const A = (depA, depB) => ({
  do(){
    //do stuff
  }
})

bottle.service('A', A, 'depA', 'depB')
```

Though this code won't work since bottlejs calls `new` on passed function which isn't allowed for ES6 arrow function. 

I've changed `return new Service()` to `return Service()` in `function service(name, Service)` and it seem to work fine, but I had no time to look deeper and see if it can influence something. Can you advise, please? Also, do you use `new` there for some particular reason?

I want to use arrow functions, because I load all services from files and reserving another name for function there would be not good, while I'm maintaining code base with eslint auto-fix for ES6, so it'll change any anonymous `function` to arrow by default

Thanks

**Comment by young-steveo** [comment]
Hi @oleksiipysanko, thanks!

The service method expects you to pass a constructor.  As an alternative, you could use the factory method which expects a callable function, so this should work:

```js
const A = (depA, depB) => ({
  do(){
    //do stuff
  }
});

bottle.factory('A', container => {
    return A(container.depA, container.depB);
});
```

**Comment by oleksiipysanko** [comment]
Hi, @young-steveo, thanks for quick follow up.

Yes, I saw such solution in other issue and doc, just was wondering if I can make a fork with this modification and not brake anything. 

In any case, there's nothing else, thanks!
