### ISSUE TITLE
String "" don't work for Bottle.pop(name)

### ISSUE THREAD

**Issue by Coburn37** [young-steveo/bottlejs#79]
Passing `""` or `"0"` to `Bottle.pop()` and then trying to do the same thing again will result in 2 different bottle objects.

   `Bottle.pop("0") !== Bottle.pop("0");` //These do not equal each other when they should...

I checked out `src/Bottle/pop.js` and it looks like it does an `if(name)` in both `pop()` and `clear()` which would be the cause of this.

I'm not sure if this has farther reaching effects throughout the code base.

**Comment by Coburn37** [comment]
I was mistaken that it was both `""` and `"0"`, it's just `""`.

**Comment by young-steveo** [comment]
@Coburn37 I think it's a good addition, even if it only covers an edge case. Thanks for the PR!
