### ISSUE TITLE
injecting services by name only

### ISSUE THREAD

**Issue by pocketmax** [young-steveo/bottlejs#83]
I know the docs say to add the names of the dependencies in the service config and as arguments in the constructor but is there a way to inject the dependencies purely by their names in the constructor?

i.e. from this...
```js
bottle.service('Beer', function (Barley, Hops, Water){
},'Barley','Hops','Water');
```

i.e. to this...
```js
bottle.service('Beer', function (Barley, Hops, Water){
});
```
-Thanks

**Comment by cjsaylor** [comment]
@pocketmax This is similar to how Angular works, but I think it is actually a bad practice. Most JS minifiers will change variable names to shorten them which would then break the lookup for getting the dependency.

IE, in your example:

```js
bottle.service('Beer', function (Barley, Hops, Water) {
});
```

might get minified to this:

```js
a.service('Beer', function (a, b, c) {
});
```

Minifiers can't minify defined strings, so a minified version of how it is currently defined in Bottlejs looks like this:

```js
a.service('Beer', function (a, b, c) {
}, 'Barley', 'Hops', 'Water');
```

Even though it got minified, the string dependencies are preserved and would be put into `a`, `b`, and `c` respectively.

**Comment by pocketmax** [comment]
Sorry, I forgot to mention I wouldn't be minifying my code since it would be running in node. But I found a hacky work around using a JS parser so thanks for the help.

**Comment by young-steveo** [comment]
@pocketmax Yeah, @cjsaylor's explanation is the reason why bottle doesn't support it.  I'm glad you found a workaround that works for you.
