### ISSUE TITLE
TypeScript: How to customize types definition of bottle.container ?

### ISSUE THREAD

**Issue by Toilal** [young-steveo/bottlejs#84]
I'm using bottlejs with TypeScript, but I need to write this anoying stuff to make TypeScript compiler happy.

```typescript
// I don't use TypeScript to finally write this :(
(bottle.container as any).MapCache as MapCache; 
```

It seems to be possible to extend typings definitions with [declarations merge features](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), but I can't make it work.

In `typings.d.ts`, I have other declarations, and when I try to write this one:
```typescript
declare module Bottle {
    import MapCAche from "./utils/mapcache"; // This is a .ts module, not a .d.ts definition file

    interface IContainer {
        MapCache: MapCache;
    }
}
```

It gives a compiler error : `TS1147:Import declarations in a namespace cannot reference a module`.

Any idea to make it work ? How to add types definition on the container ?

**Comment by Toilal** [comment]
I read the TypeScript doc page about declarations merge until the end, and I found the answer in the last section :). This example just work as expected :

```
import Bottle from "bottlejs";
import MapCache from "./utils/mapcache";

let bottle = new Bottle();
bottle.service("MapCache", () => MapCache);

export default bottle;

declare module "bottlejs" { // Use the module name
    interface IContainer {
        MapCache: MapCache;
    }
}

**Comment by wouterlemcke** [comment]
Is there a way this could work with dynamic named properties?
We define our services like `bottle.service(EventService.name, EventService)`, and retrieve it by using the name property again: `container[EventService.name]`.

But how would you define that in the interface?
