### ISSUE TITLE
Flowtype support?

### ISSUE THREAD

**Issue by dearsaturn** [young-steveo/bottlejs#90]
Is there a plan to add flowtype support, or should we just convert the existing typescript definitions?

**Comment by young-steveo** [comment]
@dearsaturn I don't personally use TypeScript or Flow, so I do not have any plans to support Flow.

That being said, I do have a [typescript def file](https://github.com/young-steveo/bottlejs/blob/master/dist/bottle.d.ts) that was contributed by the community, and the bottle API is small enough that it has not been too difficult for me to maintain the file in this repo when new features are added to Bottle.

If the level of maintenance is low for Flow support, I would consider allowing it to be distributed alongside the TypeScript def, but someone would need to do the upfront work to get it started and verify that it works properly.

**Comment by dearsaturn** [comment]
Hmm, I wouldn't mind taking a crack at it. `flowgen` might be able to convert the definitions straightaway.

**Comment by young-steveo** [comment]
I'm going to close this for now.  If you want to contribute the flowtype files, I'll welcome the pull request.

**Comment by dearsaturn** [comment]
I've moved away from `Flowtype` myself, I think it'll be more useful to everyone to make an attempt with jsDoc instead, since that'll require no transpilation step. I've just yet to think through how best to do that, though.
