### ISSUE TITLE
resetProviders() does not seem to reset nested containers after 1.6.2

### ISSUE THREAD

**Issue by abraini-Nascent** [young-steveo/bottlejs#98]
After updating to 1.6.2 our tests fail as in our `afterEach()` we call a `resetProviders()` on the bottle.  The next test will fail as the bottle does not have any of the nested containers initialized.

For now we've locked to 1.6.1
Thanks!

**Comment by young-steveo** [comment]
Thanks for the report!  I'll see if I can reproduce the issue.

**Comment by young-steveo** [comment]
New version: https://github.com/young-steveo/bottlejs/releases/tag/v1.6.3
